version: "3.1"

services:

  nginx-1.15:
    env_file:
      - .env
    build:
      context: ./docker/
      dockerfile: nginx1.15/Dockerfile
    volumes:
      - ${WEB_PATH}/:/www/wwwroot/:rw
      - ./config/nginx1.15/:/etc/nginx/conf.d/:ro
      - ./log/nginx1.15/:/var/log/nginx/:rw
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    links:
      - php-7.2
    networks:
      - backend
      - frontend

  php-7.2:
    build:
      context: ./docker/
      dockerfile: php7.2/Dockerfile
    volumes:
      - ${WEB_PATH}/:/www/wwwroot/:rw
      - ./config/php7.2/php.ini:/usr/local/etc/php/php.ini:ro
    links:
      - mysql-5.7
    networks:
      - backend

  mysql-5.7:
    env_file:
      - .env
    build:
      context: ./docker/
      dockerfile: mysql5.7/Dockerfile
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./config/mysql5.7/my.cnf:/etc/mysql/my.cnf:ro
      - ./data/mysql5.7/:/var/lib/mysql/:rw
      - ./log/mysql5.7/:/var/log/mysql/:rw
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
